#ifndef MESSAGESDOCKWIDGET_H
#define MESSAGESDOCKWIDGET_H

#include <QDockWidget>

class QTabWidget;
class QTextEdit;

/**
	@brief Manages the controls to display textual input/output to the player. For example

	- UnitDescription: Description of the problem that player should solve in the active unit
	- ToolsOutput: Warnings, errors, and other output generated by compilers, linkers, debuggers
	- PlayerSolutionInOut: Standard input sent and standard output generated by player's solution
 */
class MessagesDockWidget : public QDockWidget
{
	Q_OBJECT
	Q_DISABLE_COPY(MessagesDockWidget)

  protected:
	/// Manages the tabs for output generated by build and debug tools
	QTabWidget* messagesTabWidget;
	/// A control to display compiler, linker and debugger output
	QTextEdit* toolsOutput;

  public:
	/// Constructor
	explicit MessagesDockWidget(QWidget* parent = nullptr, Qt::WindowFlags flags = 0);
	/// Destructor
	~MessagesDockWidget();
};

#endif // MESSAGESDOCKWIDGET_H
