#include "MessagesDockWidget.h"
#include <QTabWidget>
#include <QTextEdit>

MessagesDockWidget::MessagesDockWidget(QWidget* parent, Qt::WindowFlags flags)
	: QDockWidget("Messages", parent, flags)
{
	// Each message control is placed within a tab control
	messagesTabWidget = new QTabWidget(this);
	setWidget(messagesTabWidget);

	// Add the first tab (page): the unit problem description
	// ToDo: convert it from a dialog to a widget

	// Add the second tab: output generated by build and debug tools
	toolsOutput = new QTextEdit();
	QIcon iconToolsOutput(":/button_code_editor.svg");
	messagesTabWidget->addTab(toolsOutput, iconToolsOutput, tr("Tools output"));

	// ToDo: Add a third tab: for player's solution input/output
}

MessagesDockWidget::~MessagesDockWidget()
{
}
