#ifndef MESSAGESDOCKWIDGET_H
#define MESSAGESDOCKWIDGET_H

#include <QDockWidget>

class Compiler;
class Diagnostic;
class QTabWidget;
class QTextEdit;

/**
	@brief Manages the controls to display textual input/output to the player. For example

	- UnitDescription: Description of the problem that player should solve in the active unit
	- ToolsOutput: Warnings, errors, and other output generated by compilers, linkers, debuggers
	- PlayerSolutionInOut: Standard input sent and standard output generated by player's solution
 */
class MessagesDockWidget : public QDockWidget
{
	Q_OBJECT
	Q_DISABLE_COPY(MessagesDockWidget)

  protected:
	/// Manages the tabs for output generated by build and debug tools
	QTabWidget* messagesTabWidget;
	/// Displays the current unit description
	QTextEdit* unitDescription;
	/// A control to display compiler, linker and debugger output
	QTextEdit* toolsOutput;

  public:
	/// Constructor
	explicit MessagesDockWidget(QWidget* parent = nullptr, Qt::WindowFlags flags = 0);
	/// Destructor
	~MessagesDockWidget();
	/// Display the given text in the unit description area, and makes it active if the second
	/// parameter is true
	void setUnitDescription(const QString& description, bool makeActiveTab);

  public slots:
	/// Called when a build process (compiling and linking) has finished, and ther are results
	/// The compiler pointer is required in order to get the diagnostics. If there are errors
	/// and the messages dock widget is hidden, it is made visible and the tools output tab is
	/// made active. If there are not errors, the tools output tab is just cleared.
	void buildFinished(Compiler* compiler);

  protected:
	/// Appends the given diagnostic to the tools output
	void appendDiagnostic(const Diagnostic* diagnostic);
};

#endif // MESSAGESDOCKWIDGET_H
