#ifndef COMPILERDIAGNOSTIC_H
#define COMPILERDIAGNOSTIC_H

#include "Diagnostic.h"

class QRegularExpressionMatch;

/**
	@brief A warning or error message generated by the compiler
 */
class CompilerDiagnostic : public Diagnostic
{
  public:
	/// Constructor
	CompilerDiagnostic(const QRegularExpressionMatch& match);
	/// Destructor
	~CompilerDiagnostic();
	/// Generates a text line to the user, in order to understand the diagnostic
	virtual QString buildUserText() const override;
};

#endif // COMPILERDIAGNOSTIC_H
