#ifndef LINKERDIAGNOSTIC_H
#define LINKERDIAGNOSTIC_H

#include "Diagnostic.h"

/**
	@brief A warning or error message generated by the linker
 */
class LinkerDiagnostic : public Diagnostic
{
  public:
	/// Constructor
	/// @param text A text line generated by the compiler as output
	LinkerDiagnostic(const QString& text);
	/// Destructor
	~LinkerDiagnostic();
	/// Generates a text line to the user, in order to understand the diagnostic
	virtual QString buildUserText() const override;
	/// Overrides the color to make linker diagnostics allways purple
	virtual QColor getSeverityColor() const override { return Qt::magenta; }
};

#endif // LINKERDIAGNOSTIC_H
