#ifndef CALLSTACK_H
#define CALLSTACK_H

#include "RectLayoutItem.h"

#include <QStack>

class GdbItemTree;
class MemoryFrame;

/**
	Manages the stack of function calls for an execution thread. This class is able to do
	function call operations such as:

	- raise a stack frame when a function is called (from the CPU core's memory interface)
	- dive the stack frame (function call) when the function returns,
	- show a stack frame on top of others temporally when user selects it or during parameter-passing
*/
class CallStack : public RectLayoutItem
{
  protected:
	/// The memory address of the first byte assigned for stack memory to this execution thread
	size_t startByte = 0;
	/// The size in bytes of each memory row of the stack segment
	size_t rowSize = 0;
	/// The stack of frames or function calls
	QStack<MemoryFrame*> stackFrames;
	/// Default number of rows in CPU cores
	qreal cpuCoreRows = 0.0;

  public:
	/// Constructor
	CallStack(size_t startByte, size_t rowSize, qreal zValue, QGraphicsItem* graphicsParentItem, qreal cpuCoreRows);
	/// Animate a function call
	/// @param tree The GDB's tree generated by a breakpoint hit at the called function body
	/// @return The milliseconds required by the animation
	int callFunction(const GdbItemTree& tree);
};

#endif // CALLSTACK_H
